// const age = 12;
// if(age >=18){
//     console.log('bot')
// }
// else{
//     console.log('gumau')
// }
// age >= 18 ? console.log('vote') : console.log('gum')
// age >= 18 ? console.log('vote') : console.log('gum')

//  let price = 500;
//  const isLeader = true; 
//  if(isLeader == false){
//     price = 0;
//  }
//  else{
//     price = price + 100;
//  }
//  console.log(price)
// price = isLeader === true ? console.log(price = 0) : console.log(price + 100)


//  let price = 500;
//  const isLeader = true;
 
// if(isLeader === false){
// if(price > 1000){
//     price = price / 2;
// }
// else{
//     price = 0;
// }
// }
// else{
//     price = price + 1000;
// }
// console.log(price)


let price = 500;
 const isLeader = true;

// price = isLeader == false ? price > 1000 ? console.log(price = price / 2) : console.log(price = 0) : console.log(price = price + 1000);
  
price = isLeader == false ?
 price > 1000 ?
  console.log(price = price / 2)
   : console.log(price = 0)
    : console.log(price = price + 1000);


 